project:
  type: default
  pre-render:  Rscript -e "renv::activate(); renv::restore()"

cache: true

format:
  html:
    quarto-required: ">=1.7.13"
    theme: cyborg
    toc: true
    toc-depth: 3
    toc-location: left-body
    code-fold: false
    code-overflow: wrap
    code-line-numbers: false
    code-link: true
    code-copy: true
    anchor-sections: true
    fontsize: 1.1em
    linestretch: 1.5
    smooth-scroll: true
    email-obfuscation: javascript

    



